### ISSUE TITLE
[FEATURE] Executable on unobfuscating NAA

### ISSUE THREAD

**Issue by fatmeat** [Mayyhem/SharpSCCM#34]
**Describe the solution you'd like**
Hello Mayyhem, is it possible to release a separated executable on unobfuscating NAA policy?
I fail to complie the source code in my environment.

**Comment by Mayyhem** [comment]
Hey @fatmeat! As of PR #28, deobfuscation of secret policies should happen automatically, but you can also use the DeobfuscateSecretString project within the SharpSCCM solution to deobfuscate the strings too. Does that answer your question? What errors does the compiler display when you try to build the solution?

**Comment by fatmeat** [comment]
Hello Mayyhem, thank you for the reply!
Below error prompt when I complie the DeobfuscateSecretString

D:\Github\SharpSCCM\DeobfuscateSecretString>g++ DeobfuscateSecretString.cpp
DeobfuscateSecretString.cpp: In function 'HRESULT {anonymous}::HexDecode(LPCWSTR, BYTE**, LPDWORD)':
DeobfuscateSecretString.cpp:30:50: error: 'CRYPT_STRING_HEX' was not declared in this scope
         if (CryptStringToBinaryW(pwszGarbled, 0, CRYPT_STRING_HEX, nullptr, nGarbledSize, nullptr, nullptr)) {
                                                  ^~~~~~~~~~~~~~~~
DeobfuscateSecretString.cpp:30:107: error: 'CryptStringToBinaryW' was not declared in this scope
         if (CryptStringToBinaryW(pwszGarbled, 0, CRYPT_STRING_HEX, nullptr, nGarbledSize, nullptr, nullptr)) {
                                                                                                           ^
DeobfuscateSecretString.cpp: In function 'HRESULT DES::DecryptBuffer(LPBYTE, DWORD, {anonymous}::THeaderInfo*, DWORD, BYTE**, LPDWORD)':
DeobfuscateSecretString.cpp:44:9: error: 'HCRYPTPROV' was not declared in this scope
         HCRYPTPROV hProv;
         ^~~~~~~~~~
DeobfuscateSecretString.cpp:45:35: error: 'hProv' was not declared in this scope
         if (CryptAcquireContextW(&hProv, nullptr, nullptr, PROV_RSA_AES, CRYPT_VERIFYCONTEXT)) {
                                   ^~~~~
DeobfuscateSecretString.cpp:45:60: error: 'PROV_RSA_AES' was not declared in this scope
         if (CryptAcquireContextW(&hProv, nullptr, nullptr, PROV_RSA_AES, CRYPT_VERIFYCONTEXT)) {
                                                            ^~~~~~~~~~~~
DeobfuscateSecretString.cpp:45:74: error: 'CRYPT_VERIFYCONTEXT' was not declared in this scope
         if (CryptAcquireContextW(&hProv, nullptr, nullptr, PROV_RSA_AES, CRYPT_VERIFYCONTEXT)) {
                                                                          ^~~~~~~~~~~~~~~~~~~
DeobfuscateSecretString.cpp:45:93: error: 'CryptAcquireContextW' was not declared in this scope
         if (CryptAcquireContextW(&hProv, nullptr, nullptr, PROV_RSA_AES, CRYPT_VERIFYCONTEXT)) {
                                                                                             ^
DeobfuscateSecretString.cpp:46:13: error: 'HCRYPTHASH' was not declared in this scope
             HCRYPTHASH hHash;
             ^~~~~~~~~~
DeobfuscateSecretString.cpp:47:40: error: 'CALG_SHA' was not declared in this scope
             if (CryptCreateHash(hProv, CALG_SHA, 0, 0, &hHash)) {
                                        ^~~~~~~~
DeobfuscateSecretString.cpp:47:57: error: 'hHash' was not declared in this scope
             if (CryptCreateHash(hProv, CALG_SHA, 0, 0, &hHash)) {
                                                         ^~~~~
DeobfuscateSecretString.cpp:47:62: error: 'CryptCreateHash' was not declared in this scope
             if (CryptCreateHash(hProv, CALG_SHA, 0, 0, &hHash)) {
                                                              ^
DeobfuscateSecretString.cpp:48:60: error: 'CryptHashData' was not declared in this scope
                 if (CryptHashData(hHash, pbKey, nKeySize, 0)) {
                                                            ^
DeobfuscateSecretString.cpp:49:21: error: 'HCRYPTKEY' was not declared in this scope
                     HCRYPTKEY hKey;
                     ^~~~~~~~~
DeobfuscateSecretString.cpp:51:92: error: 'hKey' was not declared in this scope
                     if (CryptDeriveKey(hProv, pHeader->nAlgorithm, hHash, pHeader->nFlag, &hKey)) {
                                                                                            ^~~~
DeobfuscateSecretString.cpp:51:96: error: 'CryptDeriveKey' was not declared in this scope
                     if (CryptDeriveKey(hProv, pHeader->nAlgorithm, hHash, pHeader->nFlag, &hKey)) {
                                                                                                ^
DeobfuscateSecretString.cpp:54:82: error: 'CryptDecrypt' was not declared in this scope
                         if (CryptDecrypt(hKey, 0, TRUE, 0, pData, &dwDecryptedLen)) {
                                                                                  ^
DeobfuscateSecretString.cpp:61:46: error: 'CryptDestroyHash' was not declared in this scope
                         CryptDestroyHash(hKey);
                                              ^
DeobfuscateSecretString.cpp:64:39: error: 'CryptDestroyHash' was not declared in this scope
                 CryptDestroyHash(hHash);
                                       ^
DeobfuscateSecretString.cpp:66:41: error: 'CryptReleaseContext' was not declared in this scope
             CryptReleaseContext(hProv, 0);
                                         ^

**Comment by Mayyhem** [comment]
@fatmeat , the exe for DeobfuscateSecretString does not need to be ran from a ConfigMgr client. Could you please paste redacted screenshots of the output of the commands you used to obtain the secret string you're trying to reverse and the output of DeobfuscateSecretString? If you'd like to send privately, please message me on the BloodHoundGang Slack. I'm @Mayyhem there too.

**Comment by Mayyhem** [comment]
Any luck @fatmeat ?

**Comment by ClickyFingerz** [comment]
@fatmeat I just want to bump this one more time before closing this issue. Were you able to resolve this issue?

**Comment by Mayyhem** [comment]
@fatmeat I just want to bump this one more time before closing this issue. Were you able to resolve this issue?

**Comment by fatmeat** [comment]
@Mayyhem Sorry for the late reply, it works on other endpoint. I'm gonna close this, thank you so much!
